"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os

from decouple import config as env_variable
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_variable(
    'DJANGO_SECRET_KEY', default='django-insecure-yak!t29py9fugi68cq=)p&c3m4z6fi&%32d(+l1!7cagb5su&-'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(env_variable('DJANGO_DEBUG', default=False))

ALLOWED_HOSTS = ["192.168.0.104", "127.0.0.1", "192.168.0.139", "192.168.212.217"]


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # modules
    'compressor',
    'django_social_share',
    'ckeditor_uploader',
    'ckeditor',

    # apps
    'articles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'articles.context_processors.get_parent_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_L10N = True

USE_TZ = True

def gettext(s):
    return s


LANGUAGES = (
    ('ru', gettext('Russian')),
    ('uk', gettext('Ukraine')),
)

# месторасположение файлов перевода
LOCALE_PATHS = (
    #'locale',
    os.path.join(BASE_DIR, 'locale'),
)

# Model translations settings
MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
MODELTRANSLATION_TRANSLATION_REGISTRY = 'src.translation'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media settings
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
MEDIA_URL = '/media/'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

# Compress settings
COMPRESS_ROOT = os.path.join(BASE_DIR, "all_static/")
COMPRESS_PRECOMPILERS = (
    ('text/scss', 'django_libsass.SassCompiler'),
)

# CKEditor config
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_UPLOAD_PATH = "fb/uploads/"

CKEDITOR_CONFIGS = {
    # http://ckeditor.com/latest/samples/toolbarconfigurator/index.html#basic
    'default': {
        'skin': 'moono-lisa',
        # 'skin': 'office2013',
        'toolbar': 'Basic',
        'filebrowserWindowWidth': 600,
        'filebrowserWindowHeight': 500,
        'allowedContent': True,
        'forcePasteAsPlainText': True,
        'resize_enabled': True,
        "removePlugins": "stylesheetparser",
    },
    'admin_area': {
        'width': '100%',
        'skin': 'moono-lisa',
        'toolbar': 'full',
        'filebrowserWindowWidth': 600,
        'filebrowserWindowHeight': 400,
        'allowedContent': True,
        'forcePasteAsPlainText': True,
        'resize_enabled': True,
        "removePlugins": "stylesheetparser,forms",
        'removeButtons': "Smiley,Font,FontSize",
        'toolbarGroups': [
            {'name': 'document', 'groups': ['mode', 'document', 'doctools']},
            {'name': 'clipboard', 'groups': ['clipboard', 'undo']},
            {'name': 'editing', 'groups': ['find', 'selection', 'spellchecker', 'editing']},
            '/',
            {'name': 'basicstyles', 'groups': ['basicstyles', 'cleanup']},
            {'name': 'paragraph', 'groups': ['list', 'indent', 'blocks', 'align', 'paragraph']},
            {'name': 'links', 'groups': ['links']},
            '/',
            {'name': 'styles', 'groups': ['styles']},
            {'name': 'colors', 'groups': ['colors']},
            {'name': 'insert', 'groups': ['insert']},
            {'name': 'forms', 'groups': ['forms']},
            {'name': 'tools', 'groups': ['tools']},
            {'name': 'others', 'groups': ['others']},
            {'name': 'about', 'groups': ['about']},
        ]
    },
}

CKEDITOR_CONFIGS['admin_ckeditor'] = CKEDITOR_CONFIGS['admin_area']
